version: '3'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - redis-data:/var/lib/redis:Z
  gitlab:
    restart: always
    image: 799571705565.dkr.ecr.eu-west-1.amazonaws.com/gitlab:617733d
    depends_on:
    - redis
    ports:
    - "${GITLAB_PORT}:80"
    - "${GITLAB_SSH_PORT}:22"
    - "${GITLAB_HTTPS_PORT}:443"
    volumes:
    - git-data:/home/git/data:Z
    env_file:
      - .env

volumes:
  redis-data:
  git-data:
