version: '3'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - redis-data:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - db-data:/var/lib/postgresql:Z
    env_file:
      - .env.postgres

  gitlab:
    restart: always
    image: sameersbn/gitlab:10.6.4
    depends_on:
    - redis
    - postgresql
    ports:
    - "${GITLAB_PORT}:80"
    - "${GITLAB_SSH_PORT}:22"
    volumes:
    - git-data:/home/git/data:Z
    env_file:
      - .env.gitlab
      - .env.postgres

volumes:
  db-data:
  redis-data:
  git-data:
