version: '3'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - redis-data:/var/lib/redis:Z

  postgresql:
    hostname: ${DB_HOST}
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - db-data:/var/lib/postgresql:Z
    environment:
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - DB_NAME=${DB_NAME}
    - DB_EXTENSION=${DB_EXTENSION}

  gitlab:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
    - redis
    - postgresql
    ports:
    - "${GITLAB_PORT}:80"
    - "${GITLAB_SSH_PORT}:22"
    volumes:
    - git-data:/home/git/data:Z
    env_file:
      - .env

volumes:
  db-data:
  redis-data:
  git-data:
